=== sumitup80/spqr/src/main/resources/avail_service.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid Technologies Online Tools 1.0 (https://www.liquid-technologies.com) -->
<xs:schema xmlns:urn="http://www.example.com/name" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="AVAIL_SERVICES">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="AVAIL_SERVICE">
          <xs:complexType mixed="true">
            <xs:sequence>
              <xs:element name="SERVICE_CLASS" type="xs:string" />
              <xs:element name="SERVICE_RESULT" type="xs:string" />
              <xs:element name="SERVICE_STATUS" type="xs:string" />
              <xs:element maxOccurs="unbounded" name="QUALIFIED_SERVICE">
                <xs:complexType mixed="true">
                  <xs:sequence>
                    <xs:element name="SERVICE_CODE" type="xs:string" />
                    <xs:element name="PROFILE_CODE" type="xs:string" minOccurs="0" />
                    <xs:element minOccurs="0" name="RECOMMENDED" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="SERVICE_ATTRIBUTES">
                <xs:complexType mixed="true">
                  <xs:sequence>
                    <xs:element maxOccurs="unbounded" name="ATTRIBUTE">
                      <xs:complexType mixed="true">
                        <xs:sequence>
                          <xs:element name="NAME" type="xs:string" />
                          <xs:element name="VALUE" type="xs:string" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="INTERNAL_AVAIL">
                <xs:complexType mixed="true">
                  <xs:sequence>
                    <xs:element name="EIRCOM" minOccurs="0">
                      <xs:complexType mixed="true">
                        <xs:sequence>
                          <xs:element name="FIBRE">
                            <xs:complexType mixed="true">
                              <xs:sequence>
                                <xs:element name="HAS_VUA_QS" type="xs:string" />
                                <xs:element name="HAS_BSP_QS" type="xs:string" />
                                <xs:element name="VUA_DELIVERABLE" type="xs:string" />
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>                      
                    </xs:element>
                    <xs:element name="SIRO" minOccurs="0">
          				<xs:complexType mixed="true">
            				<xs:sequence>
              					<xs:element name="PREMISES_ID" type="xs:string" />
            				</xs:sequence>
          				</xs:complexType>
        			</xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== sumitup80/spqr/src/main/resources/siro_available_services.xml
<?xml version="1.0" encoding="UTF-8"?>
<AVAIL_SERVICES xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:urn="http://www.example.com/name"  
    xsi:schemaLocation="http://www.example.com/name avail_service.xsd">
	<AVAIL_SERVICE>
          <SERVICE_CLASS>SFIB</SERVICE_CLASS>
          <SERVICE_RESULT>GREEN</SERVICE_RESULT>
          <SERVICE_STATUS>AVAILABLE</SERVICE_STATUS>
          <QUALIFIED_SERVICE>
            <SERVICE_CODE>SLS150</SERVICE_CODE>
          </QUALIFIED_SERVICE>
          <QUALIFIED_SERVICE>
            <SERVICE_CODE>SLS500</SERVICE_CODE>
            <RECOMMENDED>Y</RECOMMENDED>
          </QUALIFIED_SERVICE>
          <QUALIFIED_SERVICE>
            <SERVICE_CODE>SLS1GB</SERVICE_CODE>
            <RECOMMENDED>Y</RECOMMENDED>
          </QUALIFIED_SERVICE>
          <SERVICE_ATTRIBUTES>
            <ATTRIBUTE>
              <NAME>APPOINTMENT_REQUIRED</NAME>
              <VALUE>Y</VALUE>
            </ATTRIBUTE>
            <ATTRIBUTE>
              <NAME>APPOINTMENT_TYPE</NAME>
              <VALUE>INSTALLATION</VALUE>
            </ATTRIBUTE>
          </SERVICE_ATTRIBUTES>
          <INTERNAL_AVAIL>
            <SIRO>
              <PREMISES_ID>P000000000</PREMISES_ID>
            </SIRO>
          </INTERNAL_AVAIL>
       </AVAIL_SERVICE>
</AVAIL_SERVICES>

=== sumitup80/spqr/src/main/resources/eircom_available_services.xml
<?xml version="1.0" encoding="UTF-8"?>
<AVAIL_SERVICES xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:urn="http://www.example.com/name"  
    xsi:schemaLocation="http://www.example.com/name avail_service.xsd">
<AVAIL_SERVICE>
          <SERVICE_CLASS>SFTC</SERVICE_CLASS>
          <SERVICE_RESULT>GREEN</SERVICE_RESULT>
          <SERVICE_STATUS>AVAILABLE</SERVICE_STATUS>
          <QUALIFIED_SERVICE>
            <SERVICE_CODE>FCBPS</SERVICE_CODE>
            <PROFILE_CODE>100M_20M_R</PROFILE_CODE>
          </QUALIFIED_SERVICE>
          <QUALIFIED_SERVICE>
            <SERVICE_CODE>FCVUS</SERVICE_CODE>
            <PROFILE_CODE>100M_20M_R</PROFILE_CODE>
          </QUALIFIED_SERVICE>
          <SERVICE_ATTRIBUTES>
            <ATTRIBUTE>
              <NAME>APPOINTMENT_REQUIRED</NAME>
              <VALUE>Y</VALUE>
            </ATTRIBUTE>
            <ATTRIBUTE>
              <NAME>APPOINTMENT_TYPE</NAME>
              <VALUE>INSTALLATION</VALUE>
            </ATTRIBUTE>
          </SERVICE_ATTRIBUTES>
          <INTERNAL_AVAIL>
            <EIRCOM>
              <FIBRE>
                <HAS_VUA_QS>Y</HAS_VUA_QS>
                <HAS_BSP_QS>Y</HAS_BSP_QS>
                <VUA_DELIVERABLE>N</VUA_DELIVERABLE>
              </FIBRE>
            </EIRCOM>
          </INTERNAL_AVAIL>
        </AVAIL_SERVICE>
        <AVAIL_SERVICE>
          <SERVICE_CLASS>SFTH</SERVICE_CLASS>
          <SERVICE_RESULT>GREEN</SERVICE_RESULT>
          <SERVICE_STATUS>AVAILABLE</SERVICE_STATUS>
          <QUALIFIED_SERVICE>
            <SERVICE_CODE>FHBPS</SERVICE_CODE>
            <PROFILE_CODE>150M_20M_FR</PROFILE_CODE>
            <RECOMMENDED>Y</RECOMMENDED>
          </QUALIFIED_SERVICE>
          <QUALIFIED_SERVICE>
            <SERVICE_CODE>FHBPS1G</SERVICE_CODE>
            <PROFILE_CODE>1G_20M_F</PROFILE_CODE>
          </QUALIFIED_SERVICE>
          <QUALIFIED_SERVICE>
            <SERVICE_CODE>FHBPS300</SERVICE_CODE>
            <PROFILE_CODE>300M_20M_R</PROFILE_CODE>
            <RECOMMENDED>Y</RECOMMENDED>
          </QUALIFIED_SERVICE>
          <QUALIFIED_SERVICE>
            <SERVICE_CODE>FHBPS500</SERVICE_CODE>
            <PROFILE_CODE>500M_50M_F</PROFILE_CODE>
            <RECOMMENDED>Y</RECOMMENDED>
          </QUALIFIED_SERVICE>
          <QUALIFIED_SERVICE>
            <SERVICE_CODE>FHVUS</SERVICE_CODE>
            <PROFILE_CODE>150M_20M_FR</PROFILE_CODE>
            <RECOMMENDED>Y</RECOMMENDED>
          </QUALIFIED_SERVICE>
          <QUALIFIED_SERVICE>
            <SERVICE_CODE>FHVUS1G</SERVICE_CODE>
            <PROFILE_CODE>1G_20M_F</PROFILE_CODE>
          </QUALIFIED_SERVICE>
          <QUALIFIED_SERVICE>
            <SERVICE_CODE>FHVUS300</SERVICE_CODE>
            <PROFILE_CODE>300M_20M_R</PROFILE_CODE>
            <RECOMMENDED>Y</RECOMMENDED>
          </QUALIFIED_SERVICE>
          <QUALIFIED_SERVICE>
            <SERVICE_CODE>FHVUS500</SERVICE_CODE>
            <PROFILE_CODE>500M_50M_F</PROFILE_CODE>
            <RECOMMENDED>Y</RECOMMENDED>
          </QUALIFIED_SERVICE>
          <SERVICE_ATTRIBUTES>
            <ATTRIBUTE>
              <NAME>APPOINTMENT_REQUIRED</NAME>
              <VALUE>Y</VALUE>
            </ATTRIBUTE>
            <ATTRIBUTE>
              <NAME>APPOINTMENT_TYPE</NAME>
              <VALUE>INSTALLATION</VALUE>
            </ATTRIBUTE>
          </SERVICE_ATTRIBUTES>
          <INTERNAL_AVAIL>
            <EIRCOM>
              <FIBRE>
                <HAS_VUA_QS>Y</HAS_VUA_QS>
                <HAS_BSP_QS>Y</HAS_BSP_QS>
                <VUA_DELIVERABLE>N</VUA_DELIVERABLE>
              </FIBRE>
            </EIRCOM>
          </INTERNAL_AVAIL>
        </AVAIL_SERVICE>
</AVAIL_SERVICES>
